// HTTP Status Codes
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500
};

// Response Messages
const MESSAGES = {
  SELLER_PROFILE: {
    CREATED: "Seller profile created successfully",
    UPDATED: "Seller profile updated successfully",
    ARCHIVED: "Seller profile archived successfully",
    RESTORED: "Seller profile restored successfully",
    ACTIVATED: 'Seller profile activated successfully',
    DEACTIVATED: 'Seller profile deactivated successfully',
    SOFT_DELETED: "Seller profile deleted successfully",
    HARD_DELETED: "Seller profile permanently deleted",
    IMAGE_UPLOADED: "uploaded successfully",
    ALREADY_EXISTS: "Seller profile already exists",
    NOT_FOUND: "Seller profile not found",
    ACTIVE_NOT_FOUND: "Active seller profile not found",
    CREATE_FAILED: "Failed to create seller profile",
    UPDATE_FAILED: "Failed to update seller profile",
    ARCHIVE_FAILED: "Failed to archive seller profile",
    RESTORE_FAILED: "Failed to restore seller profile",
    DELETE_FAILED: "Failed to delete seller profile",
    HARD_DELETE_FAILED: "Failed to permanently delete seller profile",
    IMAGE_UPLOAD_FAILED: "Failed to upload image",
    GET_FAILED: "Failed to get seller profile"
  },
  PRODUCT: {
    CREATED: "Product created successfully",
    UPDATED: "Product updated successfully",
    STATUS_UPDATED: "Product status updated successfully",
    DELETED: "Product deleted successfully",
    IMAGE_UPLOADED: "Product image uploaded successfully",
    NOT_FOUND: "Product not found",
    CREATE_FAILED: "Failed to create product",
    UPDATE_FAILED: "Failed to update product",
    STATUS_UPDATE_FAILED: "Failed to update product status",
    DELETE_FAILED: "Failed to delete product",
    IMAGE_UPLOAD_FAILED: "Failed to upload product image",
    GET_FAILED: "Failed to get product",
    GET_ALL_FAILED: "Failed to get products",
    BULK_UPDATE_FAILED: "Failed to bulk update products",
    BULK_DELETE_FAILED: "Failed to bulk delete products",
    STATS_FAILED: "Failed to get product stats",
    DASHBOARD_STATS_FAILED: "Failed to get dashboard stats",
    ACTIVATED: "activated",
    DEACTIVATED: "deactivated",
    ACTIVE: "Active",
    INACTIVE: "Inactive"
  },
  CATEGORY: {
    CREATED: "Category created successfully",
    UPDATED: "Category updated successfully",
    DELETED: "Category deleted successfully",
    NOT_FOUND: "Category not found",
    NOT_ACTIVE: "Category not active",
    ALREADY_EXISTS: "Category name already exists",
    INVALID_ID: "Invalid category ID",
    INVALID_ID_FORMAT: "Invalid category ID format",
    HAS_PRODUCTS: "Cannot delete category with existing products",
    CREATE_FAILED: "Failed to create category",
    UPDATE_FAILED: "Failed to update category",
    DELETE_FAILED: "Failed to delete category",
    GET_FAILED: "Failed to get category",
    GET_ALL_FAILED: "Failed to get categories",
    GET_PRODUCTS_FAILED: "Failed to get category products",
    VALIDATION_ERROR: "Validation error"
  },
  CART: {
    ITEM_ADDED: "Item added to cart",
    ITEM_UPDATED: "Item quantity updated",
    ITEM_REMOVED: "Item removed from cart",
    CLEARED: "Cart cleared successfully",
    COUPON_APPLIED: "Coupon applied successfully",
    COUPON_REMOVED: "Coupon removed successfully",
    NOT_FOUND: "Cart not found",
    EMPTY: "Cart is empty",
    ITEM_NOT_FOUND: "Product not found in cart",
    STOCK_UNAVAILABLE: "Stock tidak tersedia",
    INSUFFICIENT_STOCK: "Stock kurang. Stock tersedia:",
    INVALID_QUANTITY: "Quantity harus integer",
    QUANTITY_REQUIRED: "Valid quantity is required",
    COUPON_CODE_REQUIRED: "Coupon code is required",
    INVALID_COUPON: "Invalid or expired coupon code",
    COUPON_EXISTS: "Please remove the current coupon before applying a new one",
    NO_COUPON_TO_REMOVE: "No coupon applied to remove",
    MINIMUM_AMOUNT_NOT_MET: "Minimum purchase amount is",
    COUPON_CATEGORY_MISMATCH: "This coupon is only valid for",
    ADD_FAILED: "Error adding item to cart",
    UPDATE_FAILED: "Error updating cart item",
    REMOVE_FAILED: "Error removing item from cart",
    CLEAR_FAILED: "Error clearing cart",
    GET_FAILED: "Error getting cart",
    COUPON_APPLY_FAILED: "Error applying coupon",
    COUPON_REMOVE_FAILED: "Error removing coupon",
    COUNT_GET_FAILED: "Error fetching cart count",
    COUPONS_GET_FAILED: "Error retrieving available coupons",
    COUPONS_RETRIEVED: "Available coupons retrieved successfully"
  },
  STORE: {
    NOT_FOUND: "Store not found",
    GET_INFO_FAILED: "Failed to get store information",
    GET_ALL_FAILED: "Failed to get stores",
    GET_PRODUCTS_FAILED: "Failed to get store products"
  },
  USER: {
    CREATED: "User created successfully",
    UPDATED: "User updated successfully",
    DELETED: "User deleted successfully",
    SOFT_DELETED: "User soft-deleted successfully",
    HARD_DELETED: "User permanently deleted",
    ACTIVATED: "User activated successfully",
    DEACTIVATED: "User deactivated successfully",
    ROLE_CHANGED: "User role changed successfully",
    STATUS_CHANGED: "User status changed successfully",
    NOT_FOUND: "User not found",
    NOT_FOUND_OR_INACTIVE: "User not found or inactive",
    ALREADY_EXISTS: "User already exists",
    INVALID_ROLE: "Invalid role",
    CREATE_FAILED: "Failed to create user",
    UPDATE_FAILED: "Failed to update user",
    DELETE_FAILED: "Failed to delete user",
    SOFT_DELETE_FAILED: "Failed to soft-delete user",
    HARD_DELETE_FAILED: "Failed to hard-delete user",
    GET_FAILED: "Failed to get user",
    GET_ALL_FAILED: "Failed to get users",
    ROLE_CHANGE_FAILED: "Failed to change user role",
    STATUS_CHANGE_FAILED: "Failed to change user status",
    ACCOUNT_DEACTIVATE_FAILED: "Error deactivating account",
    FETCH_DATA_FAILED: "Error fetching user data"
  },
  PROFILE: {
    CREATED: "Profile created successfully",
    UPDATED: "Profile updated successfully",
    ALREADY_EXISTS: "Profile already exists for this user",
    USE_PUT_TO_UPDATE: "Profile already exists for this user. Use PUT to update.",
    CREATE_FAILED: "Failed to create profile",
    UPDATE_FAILED: "Error updating profile",
    AVATAR_UPLOADED: "Avatar uploaded successfully",
    AVATAR_UPDATED: "Avatar updated successfully", 
    AVATAR_REMOVED: "Avatar removed successfully",
    AVATAR_UPLOAD_FAILED: "Failed to upload avatar",
    AVATAR_UPDATE_FAILED: "Failed to update avatar",
    AVATAR_REMOVE_FAILED: "Failed to remove avatar",
    NO_AVATAR_TO_REMOVE: "No avatar found to remove",
    AVATAR_FILE_REQUIRED: "Avatar image file is required",
    INVALID_IMAGE_TYPE: "Invalid image type for avatar. Allowed: JPG, PNG, WebP, GIF",
    AVATAR_TOO_LARGE: "Avatar file too large. Maximum size allowed is 2MB"
  },
  IMAGE: {
    INVALID_TYPE: "Invalid image type. Use 'logo' or 'banner'"
  },
  VALIDATION: {
    PRODUCT_IDS_REQUIRED: "Product IDs array is required"
  },
  AUTH: {
    LOGIN_SUCCESS: "Login successful",
    REGISTRATION_SUCCESS: "Registration successful",
    SELLER_REGISTRATION_SUCCESS: "Seller account created successfully. Please create your seller profile to start selling.",
    USER_REGISTRATION_SUCCESS: "User account created successfully.",
    LOGOUT_SUCCESS: "Logged out successfully",
    TOKEN_REFRESHED: "Token refreshed successfully",
    OTP_SENT: "OTP sent successfully",
    PASSWORD_RESET_SUCCESS: "Password has been reset successfully. A confirmation email has been sent to your email address. Please login with your new password.",
    PASSWORD_RESET_EMAIL_SENT: "If the email exists in our system, a verification code has been sent",
    USER_NOT_FOUND: "User not found",
    USER_ALREADY_EXISTS: "User already exists",
    INVALID_PASSWORD: "Invalid password",
    ACCOUNT_DEACTIVATED: "Account is deactivated. Please Contact Admin!",
    SELLER_ACCOUNT_INACTIVE: "Seller account is inactive. Please contact support!",
    REFRESH_TOKEN_NOT_PROVIDED: "Refresh token not provided",
    INVALID_REFRESH_TOKEN: "Invalid refresh token",
    REFRESH_TOKEN_REVOKED: "Refresh token has been revoked",
    USER_NOT_EXISTS_OR_INACTIVE: "User no longer exists or is inactive",
    EMAIL_REQUIRED: "Email is required",
    OTP_PASSWORD_REQUIRED: "Email, OTP, and new password are required",
    PASSWORD_TOO_SHORT: "New password must be at least 6 characters long",
    INVALID_OTP: "Invalid or expired OTP",
    USER_NOT_FOUND_OR_INACTIVE: "User not found or inactive",
    LOGIN_FAILED: "Login failed",
    REGISTRATION_FAILED: "Registration failed",
    TOKEN_REFRESH_FAILED: "Token refresh failed",
    LOGOUT_FAILED: "Logout failed",
    FORGOT_PASSWORD_FAILED: "Forgot password request failed",
    PASSWORD_RESET_FAILED: "Password reset failed",
    EMAIL_SEND_FAILED: "Failed to send verification code. Please try again later.",
    AUDIT_LOG_FAILED: "Failed to create audit log"
  }
};

module.exports = {
  HTTP_STATUS,
  MESSAGES
};